### ISSUE TITLE
IONA Values for OpenHAB

### ISSUE THREAD

**Issue by SKLD-OH3** [tobit6795/homeassistant-smartcontrol#1]
Hi Tobias,
I like to Import datas from my SmartMeter. With IR-Item from Iona my own IR-item is not useable. 
My Idea is to use NodeRed with a HTTP GET order. May we can talk about this?

**Comment by tobit6795** [comment]
i need a little bit more context here. what do you mean by ir-item? this project only supports the iona lora bridge and was not tested with other devices. in theory, others should work. btw this project wont be updated anyway as i have rewritten it do run in a docker container to send values via mqtt. 
[iona.py.txt](https://github.com/user-attachments/files/17006172/iona.py.txt)

**Comment by SKLD-OH3** [comment]
Hi Tobias,

Until last Saturday I had transferred my meter to OpenHAB using an IR reading head (Bitshake IR and Tasmota/MQTT adapter in the WLAN).

Unfortunately, the IONA reader is now connected and I am missing the data from the meter. I rely on this for a lot of analysis and control, e.g. PV surplus charging.

I had contacted the IONA team beforehand and asked them to enable queries or similar for this data. Unfortunately, all I got was a no and never ever for the future.

Perhaps your rework can also be integrated into Debian/Openhabian and I could get data again that way. Unfortunately, I have no idea how to integrate a Python script like this into OpenHAB.

I replied directly to your email, but that doesn't seem to have worked.

**Comment by tobit6795** [comment]
you will at least need to get familiar with docker and mqtt, thats the bare minimum.
here you have the docker-compose file im currently using with the image i built that contains the python script

docker-compose.yml
```yaml
version: '3'

services:
  iona:
    image: tobit6795/iona:latest
    container_name: iona
    restart: always
    env_file: .env
    environment:
      - MQTT_HOST=<mqtt_broker_hostname>
      - MQTT_BROKER_PORT=1883
      - MQTT_USER=<mqtt_broker_user>
      - MQTT_PW=<mqtt_broker_password>
      - USERNAME=<email>
      - PASSWORD=<password>
      - SERIAL=<serialnumber>
```

.env
```bash
SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
```
also i never used openhab before, but with quick research it looks like you can user mqtt similar to homeassistant.
this won't be enough i guess, in homeassistant i needed to do extra configuration to get the sensors as i havent managed to get  mqtt discovery working. alternatively you can run the python script directly on a linux server, but still, you will have to figure it out by yourself
